.PHONY: test lint build gen test-integration

test:
	go test ./...

lint:
	golangci-lint run ./...

build:
	go build ./...

gen:
	go generate ./...

test-integration:
	go test -v -tags=integration -timeout=10m ./internal/executor/kubernetes/...
