// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shipinator.proto

package shipinatorv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineRunStatus int32

const (
	PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED PipelineRunStatus = 0
	PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING     PipelineRunStatus = 1
	PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING     PipelineRunStatus = 2
	PipelineRunStatus_PIPELINE_RUN_STATUS_SUCCESS     PipelineRunStatus = 3
	PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED      PipelineRunStatus = 4
	PipelineRunStatus_PIPELINE_RUN_STATUS_CANCELED    PipelineRunStatus = 5
)

// Enum value maps for PipelineRunStatus.
var (
	PipelineRunStatus_name = map[int32]string{
		0: "PIPELINE_RUN_STATUS_UNSPECIFIED",
		1: "PIPELINE_RUN_STATUS_PENDING",
		2: "PIPELINE_RUN_STATUS_RUNNING",
		3: "PIPELINE_RUN_STATUS_SUCCESS",
		4: "PIPELINE_RUN_STATUS_FAILED",
		5: "PIPELINE_RUN_STATUS_CANCELED",
	}
	PipelineRunStatus_value = map[string]int32{
		"PIPELINE_RUN_STATUS_UNSPECIFIED": 0,
		"PIPELINE_RUN_STATUS_PENDING":     1,
		"PIPELINE_RUN_STATUS_RUNNING":     2,
		"PIPELINE_RUN_STATUS_SUCCESS":     3,
		"PIPELINE_RUN_STATUS_FAILED":      4,
		"PIPELINE_RUN_STATUS_CANCELED":    5,
	}
)

func (x PipelineRunStatus) Enum() *PipelineRunStatus {
	p := new(PipelineRunStatus)
	*p = x
	return p
}

func (x PipelineRunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineRunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipinator_proto_enumTypes[0].Descriptor()
}

func (PipelineRunStatus) Type() protoreflect.EnumType {
	return &file_shipinator_proto_enumTypes[0]
}

func (x PipelineRunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineRunStatus.Descriptor instead.
func (PipelineRunStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{0}
}

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_BUILD       JobType = 1
	JobType_JOB_TYPE_TEST        JobType = 2
	JobType_JOB_TYPE_DEPLOY      JobType = 3
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_BUILD",
		2: "JOB_TYPE_TEST",
		3: "JOB_TYPE_DEPLOY",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_BUILD":       1,
		"JOB_TYPE_TEST":        2,
		"JOB_TYPE_DEPLOY":      3,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_shipinator_proto_enumTypes[1].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_shipinator_proto_enumTypes[1]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{1}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_SUCCESS     JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELED    JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCESS",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_SUCCESS":     3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELED":    5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipinator_proto_enumTypes[2].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_shipinator_proto_enumTypes[2]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{2}
}

type ExecutionPhase int32

const (
	ExecutionPhase_EXECUTION_PHASE_UNSPECIFIED ExecutionPhase = 0
	ExecutionPhase_EXECUTION_PHASE_PENDING     ExecutionPhase = 1
	ExecutionPhase_EXECUTION_PHASE_RUNNING     ExecutionPhase = 2
	ExecutionPhase_EXECUTION_PHASE_SUCCEEDED   ExecutionPhase = 3
	ExecutionPhase_EXECUTION_PHASE_FAILED      ExecutionPhase = 4
	ExecutionPhase_EXECUTION_PHASE_CANCELED    ExecutionPhase = 5
)

// Enum value maps for ExecutionPhase.
var (
	ExecutionPhase_name = map[int32]string{
		0: "EXECUTION_PHASE_UNSPECIFIED",
		1: "EXECUTION_PHASE_PENDING",
		2: "EXECUTION_PHASE_RUNNING",
		3: "EXECUTION_PHASE_SUCCEEDED",
		4: "EXECUTION_PHASE_FAILED",
		5: "EXECUTION_PHASE_CANCELED",
	}
	ExecutionPhase_value = map[string]int32{
		"EXECUTION_PHASE_UNSPECIFIED": 0,
		"EXECUTION_PHASE_PENDING":     1,
		"EXECUTION_PHASE_RUNNING":     2,
		"EXECUTION_PHASE_SUCCEEDED":   3,
		"EXECUTION_PHASE_FAILED":      4,
		"EXECUTION_PHASE_CANCELED":    5,
	}
)

func (x ExecutionPhase) Enum() *ExecutionPhase {
	p := new(ExecutionPhase)
	*p = x
	return p
}

func (x ExecutionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_shipinator_proto_enumTypes[3].Descriptor()
}

func (ExecutionPhase) Type() protoreflect.EnumType {
	return &file_shipinator_proto_enumTypes[3]
}

func (x ExecutionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionPhase.Descriptor instead.
func (ExecutionPhase) EnumDescriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{3}
}

type CallbackStatus int32

const (
	CallbackStatus_CALLBACK_STATUS_UNSPECIFIED CallbackStatus = 0
	CallbackStatus_CALLBACK_STATUS_RUNNING     CallbackStatus = 1
	CallbackStatus_CALLBACK_STATUS_SUCCESS     CallbackStatus = 2
	CallbackStatus_CALLBACK_STATUS_FAILED      CallbackStatus = 3
	CallbackStatus_CALLBACK_STATUS_CANCELED    CallbackStatus = 4
)

// Enum value maps for CallbackStatus.
var (
	CallbackStatus_name = map[int32]string{
		0: "CALLBACK_STATUS_UNSPECIFIED",
		1: "CALLBACK_STATUS_RUNNING",
		2: "CALLBACK_STATUS_SUCCESS",
		3: "CALLBACK_STATUS_FAILED",
		4: "CALLBACK_STATUS_CANCELED",
	}
	CallbackStatus_value = map[string]int32{
		"CALLBACK_STATUS_UNSPECIFIED": 0,
		"CALLBACK_STATUS_RUNNING":     1,
		"CALLBACK_STATUS_SUCCESS":     2,
		"CALLBACK_STATUS_FAILED":      3,
		"CALLBACK_STATUS_CANCELED":    4,
	}
)

func (x CallbackStatus) Enum() *CallbackStatus {
	p := new(CallbackStatus)
	*p = x
	return p
}

func (x CallbackStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipinator_proto_enumTypes[4].Descriptor()
}

func (CallbackStatus) Type() protoreflect.EnumType {
	return &file_shipinator_proto_enumTypes[4]
}

func (x CallbackStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackStatus.Descriptor instead.
func (CallbackStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{4}
}

type PipelineRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	GitRef        string                 `protobuf:"bytes,3,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"`
	GitSha        string                 `protobuf:"bytes,4,opt,name=git_sha,json=gitSha,proto3" json:"git_sha,omitempty"`
	Status        PipelineRunStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=shipinator.v1.PipelineRunStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineRun) Reset() {
	*x = PipelineRun{}
	mi := &file_shipinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRun) ProtoMessage() {}

func (x *PipelineRun) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRun.ProtoReflect.Descriptor instead.
func (*PipelineRun) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineRun) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineRun) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

func (x *PipelineRun) GetGitSha() string {
	if x != nil {
		return x.GitSha
	}
	return ""
}

func (x *PipelineRun) GetStatus() PipelineRunStatus {
	if x != nil {
		return x.Status
	}
	return PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED
}

func (x *PipelineRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PipelineRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PipelineRun) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineRunId string                 `protobuf:"bytes,2,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	JobType       JobType                `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=shipinator.v1.JobType" json:"job_type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status        JobStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=shipinator.v1.JobStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_shipinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

func (x *Job) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type Artifact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ArtifactType   string                 `protobuf:"bytes,3,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	StorageBackend string                 `protobuf:"bytes,4,opt,name=storage_backend,json=storageBackend,proto3" json:"storage_backend,omitempty"`
	StorageLocator string                 `protobuf:"bytes,5,opt,name=storage_locator,json=storageLocator,proto3" json:"storage_locator,omitempty"`
	Checksum       string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_shipinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{2}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Artifact) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *Artifact) GetStorageBackend() string {
	if x != nil {
		return x.StorageBackend
	}
	return ""
}

func (x *Artifact) GetStorageLocator() string {
	if x != nil {
		return x.StorageLocator
	}
	return ""
}

func (x *Artifact) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	GitRef        string                 `protobuf:"bytes,2,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"`
	GitSha        string                 `protobuf:"bytes,3,opt,name=git_sha,json=gitSha,proto3" json:"git_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRunRequest) Reset() {
	*x = CreatePipelineRunRequest{}
	mi := &file_shipinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRunRequest) ProtoMessage() {}

func (x *CreatePipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRunRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePipelineRunRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetGitSha() string {
	if x != nil {
		return x.GitSha
	}
	return ""
}

type CreatePipelineRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineRun   *PipelineRun           `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipeline_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRunResponse) Reset() {
	*x = CreatePipelineRunResponse{}
	mi := &file_shipinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRunResponse) ProtoMessage() {}

func (x *CreatePipelineRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRunResponse.ProtoReflect.Descriptor instead.
func (*CreatePipelineRunResponse) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePipelineRunResponse) GetPipelineRun() *PipelineRun {
	if x != nil {
		return x.PipelineRun
	}
	return nil
}

type GetPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineRunId string                 `protobuf:"bytes,1,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRunRequest) Reset() {
	*x = GetPipelineRunRequest{}
	mi := &file_shipinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRunRequest) ProtoMessage() {}

func (x *GetPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{5}
}

func (x *GetPipelineRunRequest) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

type GetPipelineRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineRun   *PipelineRun           `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipeline_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRunResponse) Reset() {
	*x = GetPipelineRunResponse{}
	mi := &file_shipinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRunResponse) ProtoMessage() {}

func (x *GetPipelineRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRunResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineRunResponse) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{6}
}

func (x *GetPipelineRunResponse) GetPipelineRun() *PipelineRun {
	if x != nil {
		return x.PipelineRun
	}
	return nil
}

type ListPipelineRunJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineRunId string                 `protobuf:"bytes,1,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunJobsRequest) Reset() {
	*x = ListPipelineRunJobsRequest{}
	mi := &file_shipinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunJobsRequest) ProtoMessage() {}

func (x *ListPipelineRunJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunJobsRequest.ProtoReflect.Descriptor instead.
func (*ListPipelineRunJobsRequest) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{7}
}

func (x *ListPipelineRunJobsRequest) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

type ListPipelineRunJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunJobsResponse) Reset() {
	*x = ListPipelineRunJobsResponse{}
	mi := &file_shipinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunJobsResponse) ProtoMessage() {}

func (x *ListPipelineRunJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunJobsResponse.ProtoReflect.Descriptor instead.
func (*ListPipelineRunJobsResponse) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{8}
}

func (x *ListPipelineRunJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetArtifactMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactMetadataRequest) Reset() {
	*x = GetArtifactMetadataRequest{}
	mi := &file_shipinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactMetadataRequest) ProtoMessage() {}

func (x *GetArtifactMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactMetadataRequest) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{9}
}

func (x *GetArtifactMetadataRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactMetadataResponse) Reset() {
	*x = GetArtifactMetadataResponse{}
	mi := &file_shipinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactMetadataResponse) ProtoMessage() {}

func (x *GetArtifactMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactMetadataResponse) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{10}
}

func (x *GetArtifactMetadataResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type DownloadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_shipinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type DownloadArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactResponse) Reset() {
	*x = DownloadArtifactResponse{}
	mi := &file_shipinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactResponse) ProtoMessage() {}

func (x *DownloadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactResponse.ProtoReflect.Descriptor instead.
func (*DownloadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadArtifactResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadArtifactResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DownloadArtifactResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ReportExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        CallbackStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shipinator.v1.CallbackStatus" json:"status,omitempty"`
	ExitCode      *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	LogsUri       string                 `protobuf:"bytes,4,opt,name=logs_uri,json=logsUri,proto3" json:"logs_uri,omitempty"`
	ArtifactIds   []string               `protobuf:"bytes,5,rep,name=artifact_ids,json=artifactIds,proto3" json:"artifact_ids,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportExecutionStatusRequest) Reset() {
	*x = ReportExecutionStatusRequest{}
	mi := &file_shipinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportExecutionStatusRequest) ProtoMessage() {}

func (x *ReportExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{13}
}

func (x *ReportExecutionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportExecutionStatusRequest) GetStatus() CallbackStatus {
	if x != nil {
		return x.Status
	}
	return CallbackStatus_CALLBACK_STATUS_UNSPECIFIED
}

func (x *ReportExecutionStatusRequest) GetExitCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.ExitCode
	}
	return nil
}

func (x *ReportExecutionStatusRequest) GetLogsUri() string {
	if x != nil {
		return x.LogsUri
	}
	return ""
}

func (x *ReportExecutionStatusRequest) GetArtifactIds() []string {
	if x != nil {
		return x.ArtifactIds
	}
	return nil
}

func (x *ReportExecutionStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportExecutionStatusRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReportExecutionStatusRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type ReportExecutionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Phase         ExecutionPhase         `protobuf:"varint,2,opt,name=phase,proto3,enum=shipinator.v1.ExecutionPhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportExecutionStatusResponse) Reset() {
	*x = ReportExecutionStatusResponse{}
	mi := &file_shipinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportExecutionStatusResponse) ProtoMessage() {}

func (x *ReportExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_shipinator_proto_rawDescGZIP(), []int{14}
}

func (x *ReportExecutionStatusResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportExecutionStatusResponse) GetPhase() ExecutionPhase {
	if x != nil {
		return x.Phase
	}
	return ExecutionPhase_EXECUTION_PHASE_UNSPECIFIED
}

var File_shipinator_proto protoreflect.FileDescriptor

const file_shipinator_proto_rawDesc = "" +
	"\n" +
	"\x10shipinator.proto\x12\rshipinator.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/api/annotations.proto\"\xdd\x02\n" +
	"\vPipelineRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\agit_ref\x18\x03 \x01(\tR\x06gitRef\x12\x17\n" +
	"\agit_sha\x18\x04 \x01(\tR\x06gitSha\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .shipinator.v1.PipelineRunStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xe9\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fpipeline_run_id\x18\x02 \x01(\tR\rpipelineRunId\x121\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x16.shipinator.v1.JobTypeR\ajobType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.shipinator.v1.JobStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xff\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12#\n" +
	"\rartifact_type\x18\x03 \x01(\tR\fartifactType\x12'\n" +
	"\x0fstorage_backend\x18\x04 \x01(\tR\x0estorageBackend\x12'\n" +
	"\x0fstorage_locator\x18\x05 \x01(\tR\x0estorageLocator\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"m\n" +
	"\x18CreatePipelineRunRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x17\n" +
	"\agit_ref\x18\x02 \x01(\tR\x06gitRef\x12\x17\n" +
	"\agit_sha\x18\x03 \x01(\tR\x06gitSha\"Z\n" +
	"\x19CreatePipelineRunResponse\x12=\n" +
	"\fpipeline_run\x18\x01 \x01(\v2\x1a.shipinator.v1.PipelineRunR\vpipelineRun\"?\n" +
	"\x15GetPipelineRunRequest\x12&\n" +
	"\x0fpipeline_run_id\x18\x01 \x01(\tR\rpipelineRunId\"W\n" +
	"\x16GetPipelineRunResponse\x12=\n" +
	"\fpipeline_run\x18\x01 \x01(\v2\x1a.shipinator.v1.PipelineRunR\vpipelineRun\"D\n" +
	"\x1aListPipelineRunJobsRequest\x12&\n" +
	"\x0fpipeline_run_id\x18\x01 \x01(\tR\rpipelineRunId\"E\n" +
	"\x1bListPipelineRunJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.shipinator.v1.JobR\x04jobs\"=\n" +
	"\x1aGetArtifactMetadataRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"R\n" +
	"\x1bGetArtifactMetadataResponse\x123\n" +
	"\bartifact\x18\x01 \x01(\v2\x17.shipinator.v1.ArtifactR\bartifact\":\n" +
	"\x17DownloadArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"t\n" +
	"\x18DownloadArtifactResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"\x82\x03\n" +
	"\x1cReportExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.shipinator.v1.CallbackStatusR\x06status\x128\n" +
	"\texit_code\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\bexitCode\x12\x19\n" +
	"\blogs_uri\x18\x04 \x01(\tR\alogsUri\x12!\n" +
	"\fartifact_ids\x18\x05 \x03(\tR\vartifactIds\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"w\n" +
	"\x1dReportExecutionStatusResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x123\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x1d.shipinator.v1.ExecutionPhaseR\x05phase*\xdd\x01\n" +
	"\x11PipelineRunStatus\x12#\n" +
	"\x1fPIPELINE_RUN_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPIPELINE_RUN_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bPIPELINE_RUN_STATUS_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bPIPELINE_RUN_STATUS_SUCCESS\x10\x03\x12\x1e\n" +
	"\x1aPIPELINE_RUN_STATUS_FAILED\x10\x04\x12 \n" +
	"\x1cPIPELINE_RUN_STATUS_CANCELED\x10\x05*_\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_TYPE_BUILD\x10\x01\x12\x11\n" +
	"\rJOB_TYPE_TEST\x10\x02\x12\x13\n" +
	"\x0fJOB_TYPE_DEPLOY\x10\x03*\x9f\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12JOB_STATUS_SUCCESS\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x17\n" +
	"\x13JOB_STATUS_CANCELED\x10\x05*\xc4\x01\n" +
	"\x0eExecutionPhase\x12\x1f\n" +
	"\x1bEXECUTION_PHASE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTION_PHASE_PENDING\x10\x01\x12\x1b\n" +
	"\x17EXECUTION_PHASE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19EXECUTION_PHASE_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16EXECUTION_PHASE_FAILED\x10\x04\x12\x1c\n" +
	"\x18EXECUTION_PHASE_CANCELED\x10\x05*\xa5\x01\n" +
	"\x0eCallbackStatus\x12\x1f\n" +
	"\x1bCALLBACK_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CALLBACK_STATUS_RUNNING\x10\x01\x12\x1b\n" +
	"\x17CALLBACK_STATUS_SUCCESS\x10\x02\x12\x1a\n" +
	"\x16CALLBACK_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18CALLBACK_STATUS_CANCELED\x10\x042\xd5\x03\n" +
	"\x0fPipelineService\x12\x93\x01\n" +
	"\x11CreatePipelineRun\x12'.shipinator.v1.CreatePipelineRunRequest\x1a(.shipinator.v1.CreatePipelineRunResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/pipelines/{pipeline_id}/runs\x12\x8a\x01\n" +
	"\x0eGetPipelineRun\x12$.shipinator.v1.GetPipelineRunRequest\x1a%.shipinator.v1.GetPipelineRunResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/pipeline-runs/{pipeline_run_id}\x12\x9e\x01\n" +
	"\x13ListPipelineRunJobs\x12).shipinator.v1.ListPipelineRunJobsRequest\x1a*.shipinator.v1.ListPipelineRunJobsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/pipeline-runs/{pipeline_run_id}/jobs2\xc2\x02\n" +
	"\x0fArtifactService\x12\x9a\x01\n" +
	"\x13GetArtifactMetadata\x12).shipinator.v1.GetArtifactMetadataRequest\x1a*.shipinator.v1.GetArtifactMetadataResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/artifacts/{artifact_id}/metadata\x12\x91\x01\n" +
	"\x10DownloadArtifact\x12&.shipinator.v1.DownloadArtifactRequest\x1a'.shipinator.v1.DownloadArtifactResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/artifacts/{artifact_id}/download2\xb8\x01\n" +
	"\x10ExecutionService\x12\xa3\x01\n" +
	"\x15ReportExecutionStatus\x12+.shipinator.v1.ReportExecutionStatusRequest\x1a,.shipinator.v1.ReportExecutionStatusResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/executions/{execution_id}/statusB6Z4git.nonahob.net/jacob/shipinator/api/v1;shipinatorv1b\x06proto3"

var (
	file_shipinator_proto_rawDescOnce sync.Once
	file_shipinator_proto_rawDescData []byte
)

func file_shipinator_proto_rawDescGZIP() []byte {
	file_shipinator_proto_rawDescOnce.Do(func() {
		file_shipinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipinator_proto_rawDesc), len(file_shipinator_proto_rawDesc)))
	})
	return file_shipinator_proto_rawDescData
}

var file_shipinator_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_shipinator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_shipinator_proto_goTypes = []any{
	(PipelineRunStatus)(0),                // 0: shipinator.v1.PipelineRunStatus
	(JobType)(0),                          // 1: shipinator.v1.JobType
	(JobStatus)(0),                        // 2: shipinator.v1.JobStatus
	(ExecutionPhase)(0),                   // 3: shipinator.v1.ExecutionPhase
	(CallbackStatus)(0),                   // 4: shipinator.v1.CallbackStatus
	(*PipelineRun)(nil),                   // 5: shipinator.v1.PipelineRun
	(*Job)(nil),                           // 6: shipinator.v1.Job
	(*Artifact)(nil),                      // 7: shipinator.v1.Artifact
	(*CreatePipelineRunRequest)(nil),      // 8: shipinator.v1.CreatePipelineRunRequest
	(*CreatePipelineRunResponse)(nil),     // 9: shipinator.v1.CreatePipelineRunResponse
	(*GetPipelineRunRequest)(nil),         // 10: shipinator.v1.GetPipelineRunRequest
	(*GetPipelineRunResponse)(nil),        // 11: shipinator.v1.GetPipelineRunResponse
	(*ListPipelineRunJobsRequest)(nil),    // 12: shipinator.v1.ListPipelineRunJobsRequest
	(*ListPipelineRunJobsResponse)(nil),   // 13: shipinator.v1.ListPipelineRunJobsResponse
	(*GetArtifactMetadataRequest)(nil),    // 14: shipinator.v1.GetArtifactMetadataRequest
	(*GetArtifactMetadataResponse)(nil),   // 15: shipinator.v1.GetArtifactMetadataResponse
	(*DownloadArtifactRequest)(nil),       // 16: shipinator.v1.DownloadArtifactRequest
	(*DownloadArtifactResponse)(nil),      // 17: shipinator.v1.DownloadArtifactResponse
	(*ReportExecutionStatusRequest)(nil),  // 18: shipinator.v1.ReportExecutionStatusRequest
	(*ReportExecutionStatusResponse)(nil), // 19: shipinator.v1.ReportExecutionStatusResponse
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),         // 21: google.protobuf.Int32Value
}
var file_shipinator_proto_depIdxs = []int32{
	0,  // 0: shipinator.v1.PipelineRun.status:type_name -> shipinator.v1.PipelineRunStatus
	20, // 1: shipinator.v1.PipelineRun.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: shipinator.v1.PipelineRun.started_at:type_name -> google.protobuf.Timestamp
	20, // 3: shipinator.v1.PipelineRun.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 4: shipinator.v1.Job.job_type:type_name -> shipinator.v1.JobType
	2,  // 5: shipinator.v1.Job.status:type_name -> shipinator.v1.JobStatus
	20, // 6: shipinator.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	20, // 7: shipinator.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	20, // 8: shipinator.v1.Job.finished_at:type_name -> google.protobuf.Timestamp
	20, // 9: shipinator.v1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	5,  // 10: shipinator.v1.CreatePipelineRunResponse.pipeline_run:type_name -> shipinator.v1.PipelineRun
	5,  // 11: shipinator.v1.GetPipelineRunResponse.pipeline_run:type_name -> shipinator.v1.PipelineRun
	6,  // 12: shipinator.v1.ListPipelineRunJobsResponse.jobs:type_name -> shipinator.v1.Job
	7,  // 13: shipinator.v1.GetArtifactMetadataResponse.artifact:type_name -> shipinator.v1.Artifact
	4,  // 14: shipinator.v1.ReportExecutionStatusRequest.status:type_name -> shipinator.v1.CallbackStatus
	21, // 15: shipinator.v1.ReportExecutionStatusRequest.exit_code:type_name -> google.protobuf.Int32Value
	20, // 16: shipinator.v1.ReportExecutionStatusRequest.started_at:type_name -> google.protobuf.Timestamp
	20, // 17: shipinator.v1.ReportExecutionStatusRequest.finished_at:type_name -> google.protobuf.Timestamp
	3,  // 18: shipinator.v1.ReportExecutionStatusResponse.phase:type_name -> shipinator.v1.ExecutionPhase
	8,  // 19: shipinator.v1.PipelineService.CreatePipelineRun:input_type -> shipinator.v1.CreatePipelineRunRequest
	10, // 20: shipinator.v1.PipelineService.GetPipelineRun:input_type -> shipinator.v1.GetPipelineRunRequest
	12, // 21: shipinator.v1.PipelineService.ListPipelineRunJobs:input_type -> shipinator.v1.ListPipelineRunJobsRequest
	14, // 22: shipinator.v1.ArtifactService.GetArtifactMetadata:input_type -> shipinator.v1.GetArtifactMetadataRequest
	16, // 23: shipinator.v1.ArtifactService.DownloadArtifact:input_type -> shipinator.v1.DownloadArtifactRequest
	18, // 24: shipinator.v1.ExecutionService.ReportExecutionStatus:input_type -> shipinator.v1.ReportExecutionStatusRequest
	9,  // 25: shipinator.v1.PipelineService.CreatePipelineRun:output_type -> shipinator.v1.CreatePipelineRunResponse
	11, // 26: shipinator.v1.PipelineService.GetPipelineRun:output_type -> shipinator.v1.GetPipelineRunResponse
	13, // 27: shipinator.v1.PipelineService.ListPipelineRunJobs:output_type -> shipinator.v1.ListPipelineRunJobsResponse
	15, // 28: shipinator.v1.ArtifactService.GetArtifactMetadata:output_type -> shipinator.v1.GetArtifactMetadataResponse
	17, // 29: shipinator.v1.ArtifactService.DownloadArtifact:output_type -> shipinator.v1.DownloadArtifactResponse
	19, // 30: shipinator.v1.ExecutionService.ReportExecutionStatus:output_type -> shipinator.v1.ReportExecutionStatusResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_shipinator_proto_init() }
func file_shipinator_proto_init() {
	if File_shipinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipinator_proto_rawDesc), len(file_shipinator_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_shipinator_proto_goTypes,
		DependencyIndexes: file_shipinator_proto_depIdxs,
		EnumInfos:         file_shipinator_proto_enumTypes,
		MessageInfos:      file_shipinator_proto_msgTypes,
	}.Build()
	File_shipinator_proto = out.File
	file_shipinator_proto_goTypes = nil
	file_shipinator_proto_depIdxs = nil
}
