// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: shipinator.proto

package shipinatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PipelineService_CreatePipelineRun_FullMethodName   = "/shipinator.v1.PipelineService/CreatePipelineRun"
	PipelineService_CancelPipelineRun_FullMethodName   = "/shipinator.v1.PipelineService/CancelPipelineRun"
	PipelineService_RetryPipelineRun_FullMethodName    = "/shipinator.v1.PipelineService/RetryPipelineRun"
	PipelineService_GetPipelineRun_FullMethodName      = "/shipinator.v1.PipelineService/GetPipelineRun"
	PipelineService_ListPipelineRunJobs_FullMethodName = "/shipinator.v1.PipelineService/ListPipelineRunJobs"
)

// PipelineServiceClient is the client API for PipelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PipelineService exposes pipeline-run creation and read APIs.
type PipelineServiceClient interface {
	// CreatePipelineRun maps to POST /v1/pipelines/{id}/runs.
	CreatePipelineRun(ctx context.Context, in *CreatePipelineRunRequest, opts ...grpc.CallOption) (*CreatePipelineRunResponse, error)
	// CancelPipelineRun maps to POST /v1/pipeline-runs/{id}/cancel.
	CancelPipelineRun(ctx context.Context, in *CancelPipelineRunRequest, opts ...grpc.CallOption) (*CancelPipelineRunResponse, error)
	// RetryPipelineRun maps to POST /v1/pipeline-runs/{id}/retry.
	RetryPipelineRun(ctx context.Context, in *RetryPipelineRunRequest, opts ...grpc.CallOption) (*RetryPipelineRunResponse, error)
	// GetPipelineRun maps to GET /v1/pipeline-runs/{id}.
	GetPipelineRun(ctx context.Context, in *GetPipelineRunRequest, opts ...grpc.CallOption) (*GetPipelineRunResponse, error)
	// ListPipelineRunJobs maps to GET /v1/pipeline-runs/{id}/jobs.
	ListPipelineRunJobs(ctx context.Context, in *ListPipelineRunJobsRequest, opts ...grpc.CallOption) (*ListPipelineRunJobsResponse, error)
}

type pipelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPipelineServiceClient(cc grpc.ClientConnInterface) PipelineServiceClient {
	return &pipelineServiceClient{cc}
}

func (c *pipelineServiceClient) CreatePipelineRun(ctx context.Context, in *CreatePipelineRunRequest, opts ...grpc.CallOption) (*CreatePipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePipelineRunResponse)
	err := c.cc.Invoke(ctx, PipelineService_CreatePipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) CancelPipelineRun(ctx context.Context, in *CancelPipelineRunRequest, opts ...grpc.CallOption) (*CancelPipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPipelineRunResponse)
	err := c.cc.Invoke(ctx, PipelineService_CancelPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) RetryPipelineRun(ctx context.Context, in *RetryPipelineRunRequest, opts ...grpc.CallOption) (*RetryPipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryPipelineRunResponse)
	err := c.cc.Invoke(ctx, PipelineService_RetryPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) GetPipelineRun(ctx context.Context, in *GetPipelineRunRequest, opts ...grpc.CallOption) (*GetPipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineRunResponse)
	err := c.cc.Invoke(ctx, PipelineService_GetPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) ListPipelineRunJobs(ctx context.Context, in *ListPipelineRunJobsRequest, opts ...grpc.CallOption) (*ListPipelineRunJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPipelineRunJobsResponse)
	err := c.cc.Invoke(ctx, PipelineService_ListPipelineRunJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PipelineServiceServer is the server API for PipelineService service.
// All implementations must embed UnimplementedPipelineServiceServer
// for forward compatibility.
//
// PipelineService exposes pipeline-run creation and read APIs.
type PipelineServiceServer interface {
	// CreatePipelineRun maps to POST /v1/pipelines/{id}/runs.
	CreatePipelineRun(context.Context, *CreatePipelineRunRequest) (*CreatePipelineRunResponse, error)
	// CancelPipelineRun maps to POST /v1/pipeline-runs/{id}/cancel.
	CancelPipelineRun(context.Context, *CancelPipelineRunRequest) (*CancelPipelineRunResponse, error)
	// RetryPipelineRun maps to POST /v1/pipeline-runs/{id}/retry.
	RetryPipelineRun(context.Context, *RetryPipelineRunRequest) (*RetryPipelineRunResponse, error)
	// GetPipelineRun maps to GET /v1/pipeline-runs/{id}.
	GetPipelineRun(context.Context, *GetPipelineRunRequest) (*GetPipelineRunResponse, error)
	// ListPipelineRunJobs maps to GET /v1/pipeline-runs/{id}/jobs.
	ListPipelineRunJobs(context.Context, *ListPipelineRunJobsRequest) (*ListPipelineRunJobsResponse, error)
	mustEmbedUnimplementedPipelineServiceServer()
}

// UnimplementedPipelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPipelineServiceServer struct{}

func (UnimplementedPipelineServiceServer) CreatePipelineRun(context.Context, *CreatePipelineRunRequest) (*CreatePipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePipelineRun not implemented")
}
func (UnimplementedPipelineServiceServer) CancelPipelineRun(context.Context, *CancelPipelineRunRequest) (*CancelPipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPipelineRun not implemented")
}
func (UnimplementedPipelineServiceServer) RetryPipelineRun(context.Context, *RetryPipelineRunRequest) (*RetryPipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryPipelineRun not implemented")
}
func (UnimplementedPipelineServiceServer) GetPipelineRun(context.Context, *GetPipelineRunRequest) (*GetPipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipelineRun not implemented")
}
func (UnimplementedPipelineServiceServer) ListPipelineRunJobs(context.Context, *ListPipelineRunJobsRequest) (*ListPipelineRunJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPipelineRunJobs not implemented")
}
func (UnimplementedPipelineServiceServer) mustEmbedUnimplementedPipelineServiceServer() {}
func (UnimplementedPipelineServiceServer) testEmbeddedByValue()                         {}

// UnsafePipelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipelineServiceServer will
// result in compilation errors.
type UnsafePipelineServiceServer interface {
	mustEmbedUnimplementedPipelineServiceServer()
}

func RegisterPipelineServiceServer(s grpc.ServiceRegistrar, srv PipelineServiceServer) {
	// If the following call panics, it indicates UnimplementedPipelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PipelineService_ServiceDesc, srv)
}

func _PipelineService_CreatePipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).CreatePipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_CreatePipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).CreatePipelineRun(ctx, req.(*CreatePipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_CancelPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).CancelPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_CancelPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).CancelPipelineRun(ctx, req.(*CancelPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_RetryPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).RetryPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_RetryPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).RetryPipelineRun(ctx, req.(*RetryPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_GetPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).GetPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_GetPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).GetPipelineRun(ctx, req.(*GetPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_ListPipelineRunJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPipelineRunJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).ListPipelineRunJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_ListPipelineRunJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).ListPipelineRunJobs(ctx, req.(*ListPipelineRunJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PipelineService_ServiceDesc is the grpc.ServiceDesc for PipelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PipelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipinator.v1.PipelineService",
	HandlerType: (*PipelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePipelineRun",
			Handler:    _PipelineService_CreatePipelineRun_Handler,
		},
		{
			MethodName: "CancelPipelineRun",
			Handler:    _PipelineService_CancelPipelineRun_Handler,
		},
		{
			MethodName: "RetryPipelineRun",
			Handler:    _PipelineService_RetryPipelineRun_Handler,
		},
		{
			MethodName: "GetPipelineRun",
			Handler:    _PipelineService_GetPipelineRun_Handler,
		},
		{
			MethodName: "ListPipelineRunJobs",
			Handler:    _PipelineService_ListPipelineRunJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipinator.proto",
}

const (
	ArtifactService_GetArtifactMetadata_FullMethodName = "/shipinator.v1.ArtifactService/GetArtifactMetadata"
	ArtifactService_DownloadArtifact_FullMethodName    = "/shipinator.v1.ArtifactService/DownloadArtifact"
)

// ArtifactServiceClient is the client API for ArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArtifactService exposes artifact metadata and payload retrieval APIs.
type ArtifactServiceClient interface {
	// GetArtifactMetadata maps to GET /v1/artifacts/{id}/metadata.
	GetArtifactMetadata(ctx context.Context, in *GetArtifactMetadataRequest, opts ...grpc.CallOption) (*GetArtifactMetadataResponse, error)
	// DownloadArtifact maps to GET /v1/artifacts/{id}/download.
	DownloadArtifact(ctx context.Context, in *DownloadArtifactRequest, opts ...grpc.CallOption) (*DownloadArtifactResponse, error)
}

type artifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactServiceClient(cc grpc.ClientConnInterface) ArtifactServiceClient {
	return &artifactServiceClient{cc}
}

func (c *artifactServiceClient) GetArtifactMetadata(ctx context.Context, in *GetArtifactMetadataRequest, opts ...grpc.CallOption) (*GetArtifactMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactMetadataResponse)
	err := c.cc.Invoke(ctx, ArtifactService_GetArtifactMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) DownloadArtifact(ctx context.Context, in *DownloadArtifactRequest, opts ...grpc.CallOption) (*DownloadArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_DownloadArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactServiceServer is the server API for ArtifactService service.
// All implementations must embed UnimplementedArtifactServiceServer
// for forward compatibility.
//
// ArtifactService exposes artifact metadata and payload retrieval APIs.
type ArtifactServiceServer interface {
	// GetArtifactMetadata maps to GET /v1/artifacts/{id}/metadata.
	GetArtifactMetadata(context.Context, *GetArtifactMetadataRequest) (*GetArtifactMetadataResponse, error)
	// DownloadArtifact maps to GET /v1/artifacts/{id}/download.
	DownloadArtifact(context.Context, *DownloadArtifactRequest) (*DownloadArtifactResponse, error)
	mustEmbedUnimplementedArtifactServiceServer()
}

// UnimplementedArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactServiceServer struct{}

func (UnimplementedArtifactServiceServer) GetArtifactMetadata(context.Context, *GetArtifactMetadataRequest) (*GetArtifactMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifactMetadata not implemented")
}
func (UnimplementedArtifactServiceServer) DownloadArtifact(context.Context, *DownloadArtifactRequest) (*DownloadArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) mustEmbedUnimplementedArtifactServiceServer() {}
func (UnimplementedArtifactServiceServer) testEmbeddedByValue()                         {}

// UnsafeArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactServiceServer will
// result in compilation errors.
type UnsafeArtifactServiceServer interface {
	mustEmbedUnimplementedArtifactServiceServer()
}

func RegisterArtifactServiceServer(s grpc.ServiceRegistrar, srv ArtifactServiceServer) {
	// If the following call panics, it indicates UnimplementedArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactService_ServiceDesc, srv)
}

func _ArtifactService_GetArtifactMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).GetArtifactMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_GetArtifactMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).GetArtifactMetadata(ctx, req.(*GetArtifactMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_DownloadArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).DownloadArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_DownloadArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).DownloadArtifact(ctx, req.(*DownloadArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactService_ServiceDesc is the grpc.ServiceDesc for ArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipinator.v1.ArtifactService",
	HandlerType: (*ArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArtifactMetadata",
			Handler:    _ArtifactService_GetArtifactMetadata_Handler,
		},
		{
			MethodName: "DownloadArtifact",
			Handler:    _ArtifactService_DownloadArtifact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipinator.proto",
}

const (
	ExecutionService_ReportExecutionStatus_FullMethodName = "/shipinator.v1.ExecutionService/ReportExecutionStatus"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExecutionService exposes executor-to-control-plane status callbacks.
type ExecutionServiceClient interface {
	// ReportExecutionStatus maps to POST /v1/executions/{id}/status.
	ReportExecutionStatus(ctx context.Context, in *ReportExecutionStatusRequest, opts ...grpc.CallOption) (*ReportExecutionStatusResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) ReportExecutionStatus(ctx context.Context, in *ReportExecutionStatusRequest, opts ...grpc.CallOption) (*ReportExecutionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportExecutionStatusResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ReportExecutionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// ExecutionService exposes executor-to-control-plane status callbacks.
type ExecutionServiceServer interface {
	// ReportExecutionStatus maps to POST /v1/executions/{id}/status.
	ReportExecutionStatus(context.Context, *ReportExecutionStatusRequest) (*ReportExecutionStatusResponse, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) ReportExecutionStatus(context.Context, *ReportExecutionStatusRequest) (*ReportExecutionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportExecutionStatus not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_ReportExecutionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportExecutionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ReportExecutionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ReportExecutionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ReportExecutionStatus(ctx, req.(*ReportExecutionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipinator.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportExecutionStatus",
			Handler:    _ExecutionService_ReportExecutionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipinator.proto",
}
