// Code generated by MockGen. DO NOT EDIT.
// Source: git.nonahob.net/jacob/shipinator/internal/artifact (interfaces: ArtifactStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/artifact/mocks/mock_artifact.go -package=mocks git.nonahob.net/jacob/shipinator/internal/artifact ArtifactStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	artifact "git.nonahob.net/jacob/shipinator/internal/artifact"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockArtifactStore is a mock of ArtifactStore interface.
type MockArtifactStore struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactStoreMockRecorder
	isgomock struct{}
}

// MockArtifactStoreMockRecorder is the mock recorder for MockArtifactStore.
type MockArtifactStoreMockRecorder struct {
	mock *MockArtifactStore
}

// NewMockArtifactStore creates a new mock instance.
func NewMockArtifactStore(ctrl *gomock.Controller) *MockArtifactStore {
	mock := &MockArtifactStore{ctrl: ctrl}
	mock.recorder = &MockArtifactStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactStore) EXPECT() *MockArtifactStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockArtifactStore) Get(ctx context.Context, ref artifact.Ref) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ref)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockArtifactStoreMockRecorder) Get(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockArtifactStore)(nil).Get), ctx, ref)
}

// Put mocks base method.
func (m *MockArtifactStore) Put(ctx context.Context, id uuid.UUID, content io.Reader) (artifact.Ref, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, id, content)
	ret0, _ := ret[0].(artifact.Ref)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockArtifactStoreMockRecorder) Put(ctx, id, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockArtifactStore)(nil).Put), ctx, id, content)
}
