// Code generated by MockGen. DO NOT EDIT.
// Source: git.nonahob.net/jacob/shipinator/internal/executor (interfaces: Executor)
//
// Generated by this command:
//
//	mockgen -destination=internal/executor/mocks/mock_executor.go -package=mocks git.nonahob.net/jacob/shipinator/internal/executor Executor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	executor "git.nonahob.net/jacob/shipinator/internal/executor"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockExecutor) Cancel(ctx context.Context, handle executor.ExecutionHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, handle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockExecutorMockRecorder) Cancel(ctx, handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockExecutor)(nil).Cancel), ctx, handle)
}

// Status mocks base method.
func (m *MockExecutor) Status(ctx context.Context, handle executor.ExecutionHandle) (executor.ExecutionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, handle)
	ret0, _ := ret[0].(executor.ExecutionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockExecutorMockRecorder) Status(ctx, handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockExecutor)(nil).Status), ctx, handle)
}

// Submit mocks base method.
func (m *MockExecutor) Submit(ctx context.Context, spec executor.ExecutionSpec) (executor.ExecutionHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, spec)
	ret0, _ := ret[0].(executor.ExecutionHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockExecutorMockRecorder) Submit(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockExecutor)(nil).Submit), ctx, spec)
}
